Initial support for Akkoma's bubble timeline
cheeaun/phanpy pull request #858
Opened 2024-10-05 16:06 UTC by Steffo99

Closes #601.

Still very work in progress, but wanted to share it in the meantime!

## To do

- [ ] allow the timeline to be picked in the multi-column view
- [ ] check whether the bubble timeline is supported by a given Akkoma instance

2024-10-11 04:34 UTC, Steffo99 commented
Figured out how to add it to the shortcut menu, but I'm struggling to understand how to add a new input type to the shortcut settings (the `"variant"` option would need a `<select>`).

For now I've set its type to `"text"`, and I'm having the user input the string corresponding to the chosen variant manually.

## More screenshots!

![](https://github.com/user-attachments/assets/ec576078-5fef-4c51-8e48-2695f74a5aeb)

![](https://github.com/user-attachments/assets/14044222-3115-457f-ae3e-d04a5f807133)

![](https://github.com/user-attachments/assets/c473830f-2e8c-4b67-95a1-b61cd55cda55)

2024-12-09 04:24 UTC, Steffo99 commented
This works everywhere now, and even has a proper dropdown:

![](https://github.com/user-attachments/assets/fa9358a9-9545-4824-813b-b0131e9aa59f)

I think I also stumbled upon a bug in the import of shortcuts, which I think I fixed in 369935f3e54aed61526751cf3d8b551425e36203.

2024-12-09 04:28 UTC, Steffo99 commented
CCing @TheEssem, who might (or might not) be interested in this implementation, as author of https://github.com/TheEssem/mastodon/commit/07ff6d040f0692b5f2bc40247bb2915d370a1bcd

2025-01-24 21:57 UTC, donfeduardo commented
I think I managed to fix the merge conflicts on my fork without botching anything, so I have this running on my instance. If there's anything in particular you want another pair of eyes on, let me know.

2025-01-27 16:38 UTC, donfeduardo commented
This is perhaps a dumb question, and I swear I've searched, but what's the best way to deal with merge conflicts on the default PO file at src/locals/en.po? When I first merged this branch I just manually looked for the strings in question as a way to learn how the code worked, but that's impractical. When watching the build output after merging with the current release, I saw messages from lingui extract. Should I be running `npm run messages:extract` on its own, should I just run a build after a merge and let the file be replaced that way before committing it to my local repo, or is there some other best practice I should be following?

2025-01-28 00:10 UTC, Steffo99 commented
> "Should I be running npm run messages:extract on its own, should I just run a build after a merge and let the file be replaced that way before committing it to my local repo, or is there some other best practice I should be following?"
> —@donfeduardo 

I think just running a build should be enough for the relevant files to be replaced, although I never really explored how the localization system works, so perhaps @cheeaun might be able to provide a better answer :)

2025-08-22 09:00 UTC, paulo-roger commented
Thank you so much! Is it implemented?

2025-09-09 05:01 UTC, Steffo99 commented
Rebased onto 226fd6649477460f0c1fa4377def3e37a3e3c00d and reorganized commits to be atomic.

@cheeaun please have a look when you can!

2025-09-09 05:14 UTC, cheeaun commented
@Steffo99 this has been a while 😮‍💨. Would be useful to see some screenshots of this working 😁

2025-09-09 05:34 UTC, cheeaun requested changes

2025-09-09 05:34 UTC, cheeaun commented on src/components/nav-menu.jsx
> +          {(supports('@mastodon/bubble-timeline') ||
I feel that `@chuckya/bubble-timeline` would make more sense. Or maybe more specific to prevent future confusion.

2025-09-09 05:34 UTC, cheeaun commented on src/components/shortcuts-settings.jsx
> +      text: msg`Variant`,
Honestly `Variant` copy is… Maybe `Type`?

And would be great if this `Local only` copy and UI is preserved instead of overridden, separate from the Bubble-supported platforms. So it should be like `isBubbleSupported ? {text: Type, … } : {text: Local only, …}`

2025-09-09 05:34 UTC, cheeaun commented on src/components/shortcuts-settings.jsx
> +      type: 'variant',
`type: variant` is also too generic. Might as well make it `type: select` which its own schema that can work for this and future configs too. Or… `type: radio` for the radio-group UI? And then pass the `values` key with array `[{name: 'Local', value: 'local'}… `

2025-09-09 05:34 UTC, cheeaun commented on src/utils/supports.js
> +    let pleroma = instanceData?.pleroma;
This whole thing can just be 😁:

```
let { version, domain, pleroma } = getCurrentInstance();
```

The `instanceData?` with question mark is unnecessary.

2025-09-10 09:00 UTC, Steffo99 commented on src/components/shortcuts-settings.jsx
> +      text: msg`Variant`,
> Honestly Variant copy is… Maybe Type?

Done!

> And would be great if this Local only copy and UI is preserved instead of overridden

I'm not sure how to go about that without creating an exception to the `type: select` schema I've just created, since the shortcut schema is defined as a constant, so I don't think `supports` can be called there…

2025-09-10 09:13 UTC, Steffo99 commented
A few more screenshots!

<img width="1726" height="1008" alt="2025-09-10 10-59-49" src="https://github.com/user-attachments/assets/5cca97a6-8f79-4291-b62d-ecf067446ff2" />

<img width="561" height="428" alt="2025-09-10 11-2-15" src="https://github.com/user-attachments/assets/53c8dff9-774b-4ef8-9175-a17d742d98b4" />

<img width="560" height="394" alt="2025-09-10 11-3-17" src="https://github.com/user-attachments/assets/457a5aaf-b3eb-497f-abe0-735bc4b63263" />

<img width="286" height="215" alt="2025-09-10 11-7-41" src="https://github.com/user-attachments/assets/7bf3b9b5-8599-41e3-9e8e-fef4c1708153" />

<img width="281" height="200" alt="2025-09-10 11-9-05" src="https://github.com/user-attachments/assets/937ed905-e14c-4861-a535-1b8f03854f8a" />

2025-09-10 09:56 UTC, cheeaun commented on src/components/shortcuts-settings.jsx
> +      text: msg`Variant`,
I'm thinking of something like this, to be clear (no idea if this would work yet):

```js
public: [
    supports('@akkoma/bubble-timeline') ? {
      text: msg`Type`,
      name: 'type',
      type: 'select',
      options: [
        { value: 'local', label: msg`Local` },
        { value: 'bubble', label: msg`Bubble` },
        { value: 'federated', label: msg`Federated` },
      ],
    } : {
      text: msg`Local only`,
      name: 'local',
      type: 'checkbox',
    },
    {
      text: msg`Instance`,
      name: 'instance',
      type: 'text',
      placeholder: msg`Optional, e.g. mastodon.social`,
      notRequired: true,
    },
  ]
```

What do you think?

2025-09-10 10:04 UTC, cheeaun commented on src/components/shortcuts-settings.jsx
> +      text: msg`Variant`,
Oh I see, this will change the schema when saving, which makes it more important **not** to change it 🤔

I read that the API just set `bubble: true`? Maybe we can do the same here? Actually what would happen if both `local` and `bubble` set to `true`? 🙈

2025-09-10 10:14 UTC, Steffo99 commented on src/components/shortcuts-settings.jsx
> +      text: msg`Variant`,
> Oh I see, this will change the schema when saving, which makes it more important not to change it 🤔

Yeah, I tried setting `name: type` but then it caused various problems on import/export :laughing: 

> I read that the API just set bubble: true?

Yeah, though only on Mastodon, on Akkoma it uses a different route altogether *(WHICH I FORGOT TO RE-ADD **AAAAAAAAA** i'll do it later)*, and do not think will work with the `local` parameter…

2025-09-11 13:29 UTC, Steffo99 commented on src/components/shortcuts-settings.jsx
> +      text: msg`Variant`,
Done.

2025-09-11 13:45 UTC, Steffo99 commented on src/pages/public.jsx
> -      }
Do we have a way to check `supports` for the instance we're viewing, instead of the one we're logged in to?

This breaks from Mastodon to Pixelfed or between Akkoma and anything else...

2026-03-11 16:19 UTC, donfeduardo commented
It seems to be time to rebase this again, since `src/pages/public.jsx` has changed recently. Also in fixing the merge conflicts this time around I discovered a couple bugs:

1. The `endpoint` variable gets set to the bubble timeline on every load. This breaks the local and federated timelines. I solved this by changing the conditional to `if(supports('@akkoma/bubble-timeline') && variant === 'bubble')`
2. Even when that's properly set, if you switch between the bubble timeline and one of the other views, the list isn't reset. I solved this one with `if (publicIterator.endpoint && publicIterator.endpoint != endpoint) {
  publicIterator.current = undefined;
}
publicIterator.endpoint = endpoint;`

AFAICT this doesn't have any negative side effects, and the list properly reloads if the active timeline is switched.

2026-03-13 05:52 UTC, Steffo99 commented
I'm not too interested in working on rebasing this at the moment @donfeduardo, should I add you as contributor to my fork so that you can edit this pull request?

2026-03-14 17:56 UTC, donfeduardo commented
Sure, why not. I don't know if anybody else but me is even trying to use this, but I'd love to have easier merges even if I have to make them happen myself.

2026-03-15 05:52 UTC, Steffo99 commented
done!

2026-08-11 15:06 UTC, closed without merging